/** @format */

import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { ComponentProps } from "../types/component";
import Component from "../Models/Component";

import { addComponent } from "../libs/crud/post.server";
import connector from "../libs/connector";

const Home: NextPage = ({ components }: { components: ComponentProps[] }) => {
  let html: string = components[9].code;

  return (
    <>
      <Head>
        <title>Doraemon Code Helper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <div dangerouslySetInnerHTML={{ __html: raw }}></div> */}
        <div dangerouslySetInnerHTML={{ __html: html }}></div>
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  await connector();

  const components = await Component.find({});
  return {
    props: {
      components: JSON.parse(JSON.stringify(components)),
    },
  };
};
