/** @format */

import type { GetServerSideProps, NextPage, NextPageContext } from "next";
import Head from "next/head";

import { CategoryProps } from "../types/component";

import connector from "../libs/connector";

import Category from "../Models/Category";
import Card from "../components/Card";
import Test from "../components/Test";

const Home = ({ categories }: any) => {
  console.log(categories);
  return (
    <>
      <Head>
        <title>Doraemon Code Helper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex max-w-7xl m-auto gap-5">
        {categories?.map((item: any, index: number) => {
          const { name, subCategories, components } = item;
          console.log(subCategories);

          return (
            <Card
              key={index}
              category={name}
              subCategory={subCategories}
              components={components?.length}
            />
          );
        })}
      </main>
    </>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  await connector();

  const category = await Category.find({});
  return {
    props: {
      categories: JSON.parse(JSON.stringify(category)),
    },
  };
};
